name: Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    name: Test 

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: yarn install --frozen-lockfile

      # build utils package
      - run: cd ./packages/utils && yarn build && cd ../..

      # run test with fixtures
      - run: npx jest ./packages/cashc/test/generation/generation.test.ts

      #- run: yarn test --coverage
      #- run: yarn lint
      #- run: yarn spellcheck
      
      #- run: yarn coverage
